services:
  postgres:
    container_name: postgres_service
    restart: unless-stopped
    image: postgres:14.8-alpine3.18
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "psql", "-U", "User", "-d", "staff"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s
  employee_api:
    container_name: employee_service
    restart: unless-stopped
    build: ./employees_api
    ports:
      - "6542:6542"
    volumes:
      - ./employees_api:/app
    depends_on:
      postgres:
        condition: service_healthy
  task_api:
    container_name: task_service
    restart: unless-stopped
    build: ./task_api
    ports:
      - "4000:4000"
    volumes:
      - ./task_api:/app
    depends_on:
      postgres:
        condition: service_healthy